# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='services.proto',
  package='com.telenav.proto',
  serialized_pb='\n\x0eservices.proto\x12\x11\x63om.telenav.proto\"\x83\x02\n\x07\x43ontext\x12\x42\n\x13\x61pplication_context\x18\n \x02(\x0b\x32%.com.telenav.proto.ApplicationContext\x12\x34\n\x0cuser_context\x18\x14 \x01(\x0b\x32\x1e.com.telenav.proto.UserContext\x12\x42\n\x13transaction_context\x18\x1e \x01(\x0b\x32%.com.telenav.proto.TransactionContext\x12:\n\x0fnetwork_context\x18( \x01(\x0b\x32!.com.telenav.proto.NetworkContext\"e\n\x12\x41pplicationContext\x12\x16\n\x0e\x61pplication_id\x18\n \x02(\t\x12\x1d\n\x15\x61pplication_signature\x18\x14 \x02(\t\x12\x18\n\x10\x61pplication_name\x18\x1e \x02(\t\"4\n\x0bUserContext\x12\x14\n\x0csecure_token\x18\n \x02(\t\x12\x0f\n\x07user_id\x18\x14 \x01(\t\"e\n\x12TransactionContext\x12\x16\n\x0etransaction_id\x18\n \x02(\t\x12\x18\n\x10transaction_name\x18\x14 \x02(\t\x12\x1d\n\x15transaction_timestamp\x18\x1e \x02(\x04\"\x8b\x01\n\x0eNetworkContext\x12\x42\n\x0f\x63onnection_type\x18\n \x02(\x0e\x32).com.telenav.proto.InternetConnectionType\x12\x16\n\x0emobile_carrier\x18\x14 \x01(\t\x12\x11\n\tbandwidth\x18\x1e \x01(\t\x12\n\n\x02ip\x18( \x01(\t\"C\n\rServiceStatus\x12\x0e\n\x06status\x18\n \x02(\x05\x12\x0f\n\x07message\x18\x14 \x01(\t\x12\x11\n\tinfo_link\x18\x1e \x01(\t*>\n\x0eResponseFormat\x12\x08\n\x04html\x10\x64\x12\t\n\x04json\x10\xc8\x01\x12\r\n\x08protobuf\x10\xac\x02\x12\x08\n\x03xml\x10\x90\x03*=\n\x16InternetConnectionType\x12\x0b\n\x07OFFLINE\x10\n\x12\x0c\n\x08\x43\x45LLULAR\x10\x0b\x12\x08\n\x04WIFI\x10\x0c\x42\x34\n\x1a\x63om.telenav.proto.servicesB\x0fServiceProtocolH\x03P\x01\x88\x01\x01')

_RESPONSEFORMAT = descriptor.EnumDescriptor(
  name='ResponseFormat',
  full_name='com.telenav.proto.ResponseFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='html', index=0, number=100,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='json', index=1, number=200,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='protobuf', index=2, number=300,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='xml', index=3, number=400,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=770,
  serialized_end=832,
)


_INTERNETCONNECTIONTYPE = descriptor.EnumDescriptor(
  name='InternetConnectionType',
  full_name='com.telenav.proto.InternetConnectionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='OFFLINE', index=0, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CELLULAR', index=1, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WIFI', index=2, number=12,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=834,
  serialized_end=895,
)


html = 100
json = 200
protobuf = 300
xml = 400
OFFLINE = 10
CELLULAR = 11
WIFI = 12



_CONTEXT = descriptor.Descriptor(
  name='Context',
  full_name='com.telenav.proto.Context',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='application_context', full_name='com.telenav.proto.Context.application_context', index=0,
      number=10, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_context', full_name='com.telenav.proto.Context.user_context', index=1,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transaction_context', full_name='com.telenav.proto.Context.transaction_context', index=2,
      number=30, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='network_context', full_name='com.telenav.proto.Context.network_context', index=3,
      number=40, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=297,
)


_APPLICATIONCONTEXT = descriptor.Descriptor(
  name='ApplicationContext',
  full_name='com.telenav.proto.ApplicationContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='application_id', full_name='com.telenav.proto.ApplicationContext.application_id', index=0,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='application_signature', full_name='com.telenav.proto.ApplicationContext.application_signature', index=1,
      number=20, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='application_name', full_name='com.telenav.proto.ApplicationContext.application_name', index=2,
      number=30, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=299,
  serialized_end=400,
)


_USERCONTEXT = descriptor.Descriptor(
  name='UserContext',
  full_name='com.telenav.proto.UserContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='secure_token', full_name='com.telenav.proto.UserContext.secure_token', index=0,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_id', full_name='com.telenav.proto.UserContext.user_id', index=1,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=402,
  serialized_end=454,
)


_TRANSACTIONCONTEXT = descriptor.Descriptor(
  name='TransactionContext',
  full_name='com.telenav.proto.TransactionContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='transaction_id', full_name='com.telenav.proto.TransactionContext.transaction_id', index=0,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transaction_name', full_name='com.telenav.proto.TransactionContext.transaction_name', index=1,
      number=20, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transaction_timestamp', full_name='com.telenav.proto.TransactionContext.transaction_timestamp', index=2,
      number=30, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=456,
  serialized_end=557,
)


_NETWORKCONTEXT = descriptor.Descriptor(
  name='NetworkContext',
  full_name='com.telenav.proto.NetworkContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='connection_type', full_name='com.telenav.proto.NetworkContext.connection_type', index=0,
      number=10, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mobile_carrier', full_name='com.telenav.proto.NetworkContext.mobile_carrier', index=1,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bandwidth', full_name='com.telenav.proto.NetworkContext.bandwidth', index=2,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ip', full_name='com.telenav.proto.NetworkContext.ip', index=3,
      number=40, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=560,
  serialized_end=699,
)


_SERVICESTATUS = descriptor.Descriptor(
  name='ServiceStatus',
  full_name='com.telenav.proto.ServiceStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='com.telenav.proto.ServiceStatus.status', index=0,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='com.telenav.proto.ServiceStatus.message', index=1,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='info_link', full_name='com.telenav.proto.ServiceStatus.info_link', index=2,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=701,
  serialized_end=768,
)

_CONTEXT.fields_by_name['application_context'].message_type = _APPLICATIONCONTEXT
_CONTEXT.fields_by_name['user_context'].message_type = _USERCONTEXT
_CONTEXT.fields_by_name['transaction_context'].message_type = _TRANSACTIONCONTEXT
_CONTEXT.fields_by_name['network_context'].message_type = _NETWORKCONTEXT
_NETWORKCONTEXT.fields_by_name['connection_type'].enum_type = _INTERNETCONNECTIONTYPE
DESCRIPTOR.message_types_by_name['Context'] = _CONTEXT
DESCRIPTOR.message_types_by_name['ApplicationContext'] = _APPLICATIONCONTEXT
DESCRIPTOR.message_types_by_name['UserContext'] = _USERCONTEXT
DESCRIPTOR.message_types_by_name['TransactionContext'] = _TRANSACTIONCONTEXT
DESCRIPTOR.message_types_by_name['NetworkContext'] = _NETWORKCONTEXT
DESCRIPTOR.message_types_by_name['ServiceStatus'] = _SERVICESTATUS

class Context(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTEXT
  
  # @@protoc_insertion_point(class_scope:com.telenav.proto.Context)

class ApplicationContext(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _APPLICATIONCONTEXT
  
  # @@protoc_insertion_point(class_scope:com.telenav.proto.ApplicationContext)

class UserContext(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERCONTEXT
  
  # @@protoc_insertion_point(class_scope:com.telenav.proto.UserContext)

class TransactionContext(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRANSACTIONCONTEXT
  
  # @@protoc_insertion_point(class_scope:com.telenav.proto.TransactionContext)

class NetworkContext(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NETWORKCONTEXT
  
  # @@protoc_insertion_point(class_scope:com.telenav.proto.NetworkContext)

class ServiceStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVICESTATUS
  
  # @@protoc_insertion_point(class_scope:com.telenav.proto.ServiceStatus)

# @@protoc_insertion_point(module_scope)
