# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='map.common.proto',
  package='com.telenav.proto.map',
  serialized_pb='\n\x10map.common.proto\x12\x15\x63om.telenav.proto.map*\x9f\x02\n\x08RoadType\x12\x0e\n\nRT_UNKNOWN\x10\x00\x12\x0e\n\nRT_HIGHWAY\x10\x01\x12\x0f\n\x0bRT_ARTERIAL\x10\x02\x12\x0c\n\x08RT_LOCAL\x10\x03\x12\x0f\n\x0bRT_TERMINAL\x10\x04\x12\x10\n\x0cRT_FREE_RAMP\x10\x05\x12\x14\n\x10RT_ARTERIAL_RAMP\x10\x06\x12\x0c\n\x08RT_FERRY\x10\x07\x12\x11\n\rRT_LOCAL_RAMP\x10\x08\x12\x11\n\rRT_SMALL_RAMP\x10\t\x12\x0e\n\nRT_PRIVATE\x10\n\x12\x14\n\x10RT_NON_NAVIGABLE\x10\x0b\x12\x11\n\rRT_PEDESTRIAN\x10\x0c\x12\x0f\n\x0bRT_CYCLEWAY\x10\r\x12\r\n\tRT_LAYOUT\x10\x0e\x12\x0e\n\nRT_SERVICE\x10\x0f*\x92\x04\n\x10MapServiceStatus\x12\x0b\n\x06MAP_OK\x10\xc0W\x12\x13\n\x0eMAP_NO_CONTENT\x10\xc4W\x12\x14\n\x0fMAP_BAD_REQUEST\x10\x88Y\x12\x1a\n\x15MAP_SERVICE_NOT_FOUND\x10\x8cY\x12\x16\n\x11MAP_UNKNOWN_ERROR\x10\xecY\x12\x1c\n\x17MAP_SERVICE_UNAVAILABLE\x10\xefY\x12\x18\n\x13MAP_SERVICE_TIMEOUT\x10\xf0Y\x12\x11\n\x0cMAP_DB_ERROR\x10\xf6Y\x12\x16\n\x11MAP_DB_CONN_ERROR\x10\xf7Y\x12\x1a\n\x15MAP_DB_DATA_NOT_FOUND\x10\xf8Y\x12\x1b\n\x16MAP_DB_DUPLICATE_ENTRY\x10\xf9Y\x12\x14\n\x0fROUTE_NOT_FOUND\x10\xd1Z\x12\x17\n\x12ROUTE_OD_TOO_CLOSE\x10\xd2Z\x12\x15\n\x10ORIGIN_NOT_COVER\x10\xd3Z\x12\x1a\n\x15\x44\x45STINATION_NOT_COVER\x10\xd4Z\x12\x15\n\x10ORIGIN_NOT_FOUND\x10\xd5Z\x12\x1a\n\x15\x44\x45STINATION_NOT_FOUND\x10\xd6Z\x12%\n ORIGIN_DESTINATION_ACROSS_REGION\x10\xd7Z\x12\x1e\n\x19PEDESTRIAN_ROUTE_TOO_LONG\x10\xdbZ\x12\x1a\n\x15PEDESTRIAN_ON_HIGHWAY\x10\xdcZB*\n\x15\x63om.telenav.map.protoB\x0fMapCommonProtocH\x03')

_ROADTYPE = descriptor.EnumDescriptor(
  name='RoadType',
  full_name='com.telenav.proto.map.RoadType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='RT_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_HIGHWAY', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_ARTERIAL', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_LOCAL', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_TERMINAL', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_FREE_RAMP', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_ARTERIAL_RAMP', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_FERRY', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_LOCAL_RAMP', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_SMALL_RAMP', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_PRIVATE', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_NON_NAVIGABLE', index=11, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_PEDESTRIAN', index=12, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_CYCLEWAY', index=13, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_LAYOUT', index=14, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RT_SERVICE', index=15, number=15,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=44,
  serialized_end=331,
)


_MAPSERVICESTATUS = descriptor.EnumDescriptor(
  name='MapServiceStatus',
  full_name='com.telenav.proto.map.MapServiceStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MAP_OK', index=0, number=11200,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAP_NO_CONTENT', index=1, number=11204,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAP_BAD_REQUEST', index=2, number=11400,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAP_SERVICE_NOT_FOUND', index=3, number=11404,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAP_UNKNOWN_ERROR', index=4, number=11500,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAP_SERVICE_UNAVAILABLE', index=5, number=11503,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAP_SERVICE_TIMEOUT', index=6, number=11504,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAP_DB_ERROR', index=7, number=11510,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAP_DB_CONN_ERROR', index=8, number=11511,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAP_DB_DATA_NOT_FOUND', index=9, number=11512,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAP_DB_DUPLICATE_ENTRY', index=10, number=11513,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROUTE_NOT_FOUND', index=11, number=11601,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROUTE_OD_TOO_CLOSE', index=12, number=11602,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORIGIN_NOT_COVER', index=13, number=11603,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DESTINATION_NOT_COVER', index=14, number=11604,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORIGIN_NOT_FOUND', index=15, number=11605,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DESTINATION_NOT_FOUND', index=16, number=11606,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ORIGIN_DESTINATION_ACROSS_REGION', index=17, number=11607,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PEDESTRIAN_ROUTE_TOO_LONG', index=18, number=11611,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PEDESTRIAN_ON_HIGHWAY', index=19, number=11612,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=334,
  serialized_end=864,
)


RT_UNKNOWN = 0
RT_HIGHWAY = 1
RT_ARTERIAL = 2
RT_LOCAL = 3
RT_TERMINAL = 4
RT_FREE_RAMP = 5
RT_ARTERIAL_RAMP = 6
RT_FERRY = 7
RT_LOCAL_RAMP = 8
RT_SMALL_RAMP = 9
RT_PRIVATE = 10
RT_NON_NAVIGABLE = 11
RT_PEDESTRIAN = 12
RT_CYCLEWAY = 13
RT_LAYOUT = 14
RT_SERVICE = 15
MAP_OK = 11200
MAP_NO_CONTENT = 11204
MAP_BAD_REQUEST = 11400
MAP_SERVICE_NOT_FOUND = 11404
MAP_UNKNOWN_ERROR = 11500
MAP_SERVICE_UNAVAILABLE = 11503
MAP_SERVICE_TIMEOUT = 11504
MAP_DB_ERROR = 11510
MAP_DB_CONN_ERROR = 11511
MAP_DB_DATA_NOT_FOUND = 11512
MAP_DB_DUPLICATE_ENTRY = 11513
ROUTE_NOT_FOUND = 11601
ROUTE_OD_TOO_CLOSE = 11602
ORIGIN_NOT_COVER = 11603
DESTINATION_NOT_COVER = 11604
ORIGIN_NOT_FOUND = 11605
DESTINATION_NOT_FOUND = 11606
ORIGIN_DESTINATION_ACROSS_REGION = 11607
PEDESTRIAN_ROUTE_TOO_LONG = 11611
PEDESTRIAN_ON_HIGHWAY = 11612



# @@protoc_insertion_point(module_scope)
